#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# Nextcloud Deployment for OpenShift
# Just run: sh deploy.sh
# Route hostname is auto-generated by OpenShift
# ═══════════════════════════════════════════════════════════════════════════════
set -e

# Configuration
IMAGE="${NEXTCLOUD_IMAGE:-quay.io/ryan_nix/nextcloud-openshift:latest}"
NAMESPACE="${NAMESPACE:-$(oc project -q)}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()   { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
info()  { echo -e "${CYAN}[    ]${NC} $1"; }

generate_password() {
    openssl rand -base64 20 | tr -dc 'a-zA-Z0-9' | head -c 20
}

# ─────────────────────────────────────────────────────────────────────────────
# Prompt to save manifests, then export live resources after deployment.
# Secrets are intentionally excluded — they contain credentials.
# ─────────────────────────────────────────────────────────────────────────────
SAVE_MANIFESTS=false
MANIFEST_DIR="manifests"

prompt_save_manifests() {
    echo -n "Save Kubernetes manifests to ./${MANIFEST_DIR}/? [y/N]: "
    read -r SAVE_ANSWER
    if [ "$SAVE_ANSWER" = "y" ]; then
        SAVE_MANIFESTS=true
        mkdir -p "${MANIFEST_DIR}"
        log "Manifests will be saved to ./${MANIFEST_DIR}/"
    fi
}

save_manifests() {
    if [ "$SAVE_MANIFESTS" != "true" ]; then return; fi

    log "Saving manifests to ./${MANIFEST_DIR}/..."
    # Export live resources — captures actual state including route hostname.
    # Secrets are excluded; they are generated at deploy time.
    oc get deployment mariadb redis nextcloud -o yaml         | grep -v 'resourceVersion\|uid:\|creationTimestamp\|generation:\|kubectl.kubernetes.io'         > "${MANIFEST_DIR}/deployments.yaml"
    oc get service mariadb redis nextcloud -o yaml         | grep -v 'resourceVersion\|uid:\|creationTimestamp\|kubectl.kubernetes.io'         > "${MANIFEST_DIR}/services.yaml"
    oc get pvc mariadb-pvc nextcloud-data-pvc nextcloud-apps-pvc nextcloud-config-pvc -o yaml         | grep -v 'resourceVersion\|uid:\|creationTimestamp\|kubectl.kubernetes.io\|volumeName\|pv.kubernetes.io'         > "${MANIFEST_DIR}/pvcs.yaml"
    oc get route nextcloud -o yaml         | grep -v 'resourceVersion\|uid:\|creationTimestamp\|kubectl.kubernetes.io\|openshift.io/host.generated'         > "${MANIFEST_DIR}/route.yaml"
    log "✓ Manifests saved to ./${MANIFEST_DIR}/"
    info "  Note: Secrets are not saved — regenerate them with deploy.sh on a fresh install."
}

# ─────────────────────────────────────────────────────────────────────────────
# Create a secret only if it doesn't already exist.
# On re-runs this preserves existing credentials so MariaDB data and
# config.php stay in sync.
# ─────────────────────────────────────────────────────────────────────────────
create_secret_if_not_exists() {
    local NAME=$1
    shift
    if oc get secret "$NAME" &>/dev/null; then
        warn "Secret '$NAME' already exists — preserving existing credentials"
    else
        oc create secret generic "$NAME" "$@"
        log "Secret '$NAME' created"
    fi
}

post_deploy_config() {
    local ROUTE_HOST="$1"

    log "Running post-deployment configuration..."

    log "Waiting for Nextcloud to fully initialize (30s)..."
    sleep 30

    POD=$(oc get pods -l app=nextcloud -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
    if [ -z "$POD" ]; then
        warn "Could not find Nextcloud pod, skipping post-deploy config"
        return
    fi

    log "Configuring Nextcloud on pod: $POD"

    log "Adding route host to trusted domains..."
    oc exec "$POD" -- php /var/www/html/occ config:system:set trusted_domains 1 \
        --value="$ROUTE_HOST" 2>/dev/null || warn "Could not add trusted domain"

    log "Removing lost+found from custom_apps..."
    oc exec "$POD" -- rm -rf /var/www/html/custom_apps/lost+found 2>/dev/null || true

    log "Adding missing database indices..."
    oc exec "$POD" -- php /var/www/html/occ db:add-missing-indices -n \
        2>/dev/null || warn "Could not add indices"

    log "Running mimetype migrations..."
    oc exec "$POD" -- php /var/www/html/occ maintenance:repair --include-expensive -n \
        2>/dev/null || warn "Repair had issues"

    log "Verifying Nextcloud Office (richdocuments)..."
    # WOPI URL configuration is owned entirely by entrypoint.sh using NEXTCLOUD_TRUSTED_DOMAINS.
    # Do NOT set wopi_url or public_wopi_url here — overriding them breaks Collabora.
    log "Waiting for CODE server to initialize (60s)..."
    sleep 60

    if oc exec "$POD" -- php /var/www/html/occ richdocuments:activate-config 2>/dev/null; then
        log "✓ Nextcloud Office verified and ready!"
    else
        warn "CODE server still initializing - document editing available in 1-2 minutes"
    fi

    log "Post-deployment configuration complete!"
}

deploy() {
    log "═══════════════════════════════════════════════════════════════"
    log "  Nextcloud on OpenShift - Automated Deployment"
    log "═══════════════════════════════════════════════════════════════"
    echo ""
    log "Namespace: $NAMESPACE"
    log "Image:     $IMAGE"
    echo ""

    prompt_save_manifests
    echo ""

    # Passwords are only used when creating secrets for the first time.
    # On re-runs the existing secrets (and their original passwords) are kept.
    MYSQL_ROOT_PW=$(generate_password)
    MYSQL_PW=$(generate_password)
    REDIS_PW=$(generate_password)
    ADMIN_PW=$(generate_password)

    log "Creating secrets (skipped if they already exist)..."

    create_secret_if_not_exists mariadb-secret \
        --from-literal=root-password="$MYSQL_ROOT_PW" \
        --from-literal=database=nextcloud \
        --from-literal=username=nextcloud \
        --from-literal=password="$MYSQL_PW"

    create_secret_if_not_exists redis-secret \
        --from-literal=password="$REDIS_PW"

    create_secret_if_not_exists nextcloud-secret \
        --from-literal=admin-user=admin \
        --from-literal=admin-password="$ADMIN_PW"

    log "Creating PVCs..."

    cat <<EOF | oc apply -f -
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-apps-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Mi
EOF

    log "Deploying MariaDB 11.8..."

    cat <<EOF | oc apply -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: nextcloud-app
    app.openshift.io/runtime: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/part-of: nextcloud-app
    spec:
      containers:
        - name: mariadb
          image: quay.io/fedora/mariadb-118
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql/data
          resources:
            requests: { memory: 256Mi, cpu: 100m }
            limits:   { memory: 1Gi,   cpu: 1000m }
          livenessProbe:
            exec:
              command: ["sh", "-c", "mariadb-admin ping -u root -p\${MYSQL_ROOT_PASSWORD}"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["sh", "-c", "mariadb-admin ping -u root -p\${MYSQL_ROOT_PASSWORD}"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: nextcloud-app
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
EOF

    log "Deploying Redis 8..."

    cat <<EOF | oc apply -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: nextcloud-app
    app.openshift.io/runtime: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: nextcloud-app
    spec:
      containers:
        - name: redis
          image: docker.io/redis:8-alpine
          command: ["redis-server", "--requirepass", "\$(REDIS_PASSWORD)", "--save", "", "--appendonly", "no", "--stop-writes-on-bgsave-error", "no"]
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          resources:
            requests: { memory: 64Mi,  cpu: 50m }
            limits:   { memory: 256Mi, cpu: 500m }
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities: { drop: [ALL] }
            seccompProfile: { type: RuntimeDefault }
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: nextcloud-app
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
EOF

    log "Waiting for MariaDB to be ready..."
    oc wait --for=condition=available deployment/mariadb --timeout=120s \
        || warn "MariaDB taking longer than expected"

    log "Deploying Nextcloud..."

    cat <<EOF | oc apply -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/part-of: nextcloud-app
    app.openshift.io/runtime: nginx
  annotations:
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"mariadb"},
       {"apiVersion":"apps/v1","kind":"Deployment","name":"redis"}]
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/part-of: nextcloud-app
    spec:
      containers:
        - name: nextcloud
          image: ${IMAGE}
          ports:
            - containerPort: 8080
          env:
            - name: NC_MYSQL_HOST
              value: "mariadb"
            - name: NC_MYSQL_PORT
              value: "3306"
            - name: NC_MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: database
            - name: NC_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: NC_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: NC_REDIS_HOST
              value: "redis"
            - name: NC_REDIS_PORT
              value: "6379"
            - name: NC_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: admin-user
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: admin-password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "localhost"  # patched with route hostname after route creation
            - name: NC_S3_ENABLED
              value: "false"
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html/data
            - name: nextcloud-config
              mountPath: /var/www/html/config
            - name: nextcloud-apps
              mountPath: /var/www/html/custom_apps
          resources:
            requests: { memory: 256Mi, cpu: 100m }
            limits:   { memory: 1Gi,   cpu: 1000m }
          readinessProbe:
            httpGet:
              path: /status.php
              port: 8080
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities: { drop: [ALL] }
            seccompProfile: { type: RuntimeDefault }
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
        - name: nextcloud-config
          persistentVolumeClaim:
            claimName: nextcloud-config-pvc
        - name: nextcloud-apps
          persistentVolumeClaim:
            claimName: nextcloud-apps-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/part-of: nextcloud-app
spec:
  selector:
    app: nextcloud
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nextcloud
  annotations:
    haproxy.router.openshift.io/timeout: 3600s
spec:
  to:
    kind: Service
    name: nextcloud
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
EOF

    # Grab the route hostname and inject it into NEXTCLOUD_TRUSTED_DOMAINS
    # before the pod starts. This is more reliable than using occ post-boot
    # because the entrypoint applies trusted_domains from env on every start.
    ROUTE_HOST=$(oc get route nextcloud -o jsonpath='{.spec.host}')
    log "Route hostname: $ROUTE_HOST"
    log "Patching NEXTCLOUD_TRUSTED_DOMAINS with route hostname..."
    oc set env deployment/nextcloud \
        NEXTCLOUD_TRUSTED_DOMAINS="${ROUTE_HOST}"

    log "Waiting for Nextcloud to be ready..."
    oc wait --for=condition=available deployment/nextcloud --timeout=300s \
        || warn "Nextcloud taking longer than expected"

    save_manifests
    post_deploy_config "$ROUTE_HOST"

    echo ""
    log "═══════════════════════════════════════════════════════════════"
    log "  ✓ Deployment Complete!"
    log "═══════════════════════════════════════════════════════════════"
    echo ""
    info "URL: https://${ROUTE_HOST}"
    echo ""

    info "Admin credentials:"
    info "  Username: admin"
    info "  Password: $(oc get secret nextcloud-secret -o jsonpath='{.data.admin-password}' | base64 -d)"
    echo ""
    warn "Save these credentials - they won't be shown again!"
    echo ""
}

# ─────────────────────────────────────────────────────────────────────────────
# Sync MariaDB password to match the current mariadb-secret.
# Use this after a broken re-run overwrote the secret but not the database.
# ─────────────────────────────────────────────────────────────────────────────
fix_db_password() {
    log "Syncing MariaDB user password to match mariadb-secret..."

    ROOT_PW=$(oc get secret mariadb-secret -o jsonpath='{.data.root-password}' | base64 -d)
    NC_PW=$(oc get secret mariadb-secret   -o jsonpath='{.data.password}'      | base64 -d)
    MARIADB_POD=$(oc get pod -l app=mariadb -o jsonpath='{.items[0].metadata.name}')

    oc exec "$MARIADB_POD" -- \
        mariadb -u root -p"${ROOT_PW}" -e \
        "ALTER USER 'nextcloud'@'%' IDENTIFIED BY '${NC_PW}'; FLUSH PRIVILEGES;"

    log "Password synced. Restarting Nextcloud..."
    oc rollout restart deployment/nextcloud
    oc rollout status deployment/nextcloud --timeout=300s
    log "✓ Done"
}

cleanup() {
    # --keep-data: remove deployments/secrets but preserve PVCs (use for image upgrades
    #              where you intend to redeploy with the SAME secrets immediately after)
    local KEEP_DATA=false
    [[ "${2:-}" == "--keep-data" ]] && KEEP_DATA=true

    if [ "$KEEP_DATA" = false ]; then
        warn "This will delete ALL Nextcloud data including PVCs and secrets."
        warn "Run 'sh deploy.sh cleanup --keep-data' to preserve PVC data."
        echo -n "Delete all Nextcloud data? [y/N]: "
        read -r CONFIRM
        if [ "$CONFIRM" != "y" ]; then
            log "Cleanup cancelled."
            exit 0
        fi
    fi

    log "Removing deployments, services, route, and secrets..."
    oc delete deployment nextcloud mariadb redis --ignore-not-found
    oc delete service    nextcloud mariadb redis --ignore-not-found
    oc delete route      nextcloud               --ignore-not-found
    oc delete secret     nextcloud-secret mariadb-secret redis-secret --ignore-not-found

    if [ "$KEEP_DATA" = false ]; then
        log "Deleting PVCs..."
        oc delete pvc mariadb-pvc nextcloud-data-pvc nextcloud-apps-pvc nextcloud-config-pvc \
            --ignore-not-found
        log "✓ Full cleanup complete — all data removed."
    else
        warn "PVCs preserved. Redeploy immediately with the SAME secrets to avoid credential mismatch."
        warn "If you let secrets get regenerated, run: sh deploy.sh fix-db-password"
    fi
}

# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════
case "${1:-}" in
    cleanup)
        cleanup
        ;;
    fix-db-password)
        fix_db_password
        ;;
    -h|--help|help)
        echo "Nextcloud on OpenShift - Deployment Script"
        echo ""
        echo "Usage:"
        echo "  sh deploy.sh                           Deploy Nextcloud"
        echo "  sh deploy.sh fix-db-password           Sync MariaDB password to match current secret"
        echo "  sh deploy.sh cleanup                   Full teardown including PVCs (fresh start)"
        echo "  sh deploy.sh cleanup --keep-data       Remove deployments/secrets, preserve PVCs"
        echo ""
        echo "Manifest saving:"
        echo "  deploy.sh prompts to save manifests to ./manifests/ after deployment."
        echo "  Secrets are excluded (generated at runtime). Use for GitOps or re-deploy."
        echo ""
        echo "Environment variables:"
        echo "  NEXTCLOUD_IMAGE  Container image (default: quay.io/ryan_nix/nextcloud-openshift:latest)"
        echo "  NAMESPACE        Target namespace (default: current project)"
        echo ""
        echo "Examples:"
        echo "  sh deploy.sh"
        echo "  NEXTCLOUD_IMAGE=my-registry/nextcloud:v1 sh deploy.sh"
        echo "  sh deploy.sh fix-db-password"
        echo "  sh deploy.sh cleanup                   # fresh start, deletes everything"
        echo "  sh deploy.sh cleanup --keep-data       # image rebuild/upgrade workflow"
        ;;
    *)
        deploy
        ;;
esac